version: "3.9"
services:
  database:
    build: LmsPlusPlus.Database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lmsplusplus-dev
