version: "3.9"
services:
  database:
    build: LmsPlusPlus.Database
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lmsplusplus-test
