version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: "6.0"
        NODE_VERSION: "lts/*"
    volumes:
      - ..:/workspace:cached
      - ~/.aspnet/https/:/home/vscode/.aspnet/https
    command: sleep infinity
  db:
    image: postgres:14.1
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
volumes:
  postgres-data:
